language = "javascript"
framework = "express"
packageManager = "npm"
entry = "server.js"

installCommand = "npm install"
buildCommand = "npm run build"
startCommand = "npm run start:prod"
port = 8787
